version: "3.8"
services:
  web:
    #build: chemin vers Dockerfile
    build: .
    volumes:
      - ./src/chambre_hotel:/app/src/chambre_hotel
    ports:
      # - <HOST_PORT>:<CONTAINER
      - 5000:5000

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: hotel
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
